# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/FallingC_nbdev',
                'doc_host': 'https://lnicole08.github.io',
                'git_url': 'https://github.com/lnicole08/FallingC_nbdev',
                'lib_path': 'FallingC_nbdev'},
  'syms': { 'FallingC_nbdev.NLCLIMB': {},
            'FallingC_nbdev.NLGRAPHS': {},
            'FallingC_nbdev.core': {'FallingC_nbdev.core.foo': ('core.html#foo', 'FallingC_nbdev/core.py')}}}